### ISSUE TITLE
一个关于“import gl”的建议

### ISSUE THREAD

**Issue by CostaliyA** [jingjiqinggong/specp2p#1]
您针对reference edit提出的工作毫无疑问是十分出色的，然而我在复现代码时遇到modulenotfounderror: no module named 'gl'的报错，新建一个名为gl.py的文件并在该文件初始化gl，如gl=None即可正常工作。希望在后续版本能加上gl.py，谢谢！

**Comment by jingjiqinggong** [comment]
Thank you for your attention.
